### ISSUE TITLE
Add messageArgsTypes to notification

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-chat#11]
Similar to what has been done for ganomede-turngame already: https://github.com/j3k0/ganomede-turngame/commit/879fe292e54f3923b5928a56cbf697fd682ce169

Set the field containing the username to type `directory:name`

**Comment by elmigranto** [comment]
Looks like [`.push` is pulled as is from `req.body`](https://github.com/j3k0/ganomede-chat/blob/542f333752c260091eee533c2715f8c686c0502a/src/api.coffee#L162). The other thing is system messages, but those do the same except username is `$$` and type is `event`.

Maybe this one should be on clientside?

**Comment by j3k0** [comment]
Oh, that's right. Seems like I went for something quick and dirty... So we can close this, I'll fix client side.
